version: "3.3"

services:
  client:
    image: njayman/njayman
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    command: npm run serve
